num_gen = (num for num in range(1, 15, 2))
print(next(num_gen))
print(next(num_gen))
print(next(num_gen))
print(next(num_gen))
print(next(num_gen))
print(next(num_gen))
print(next(num_gen))
print(next(num_gen))
